#-------------------------------
# Site Settings
title: ~# Aaron
logo: # You can add own logo. For example '/images/logo.png'.
description: ''


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'
      

#-------------------------------
# Author Settings
author:
  name: Aaron
  avatar: '/images/me.jpeg'


#-------------------------------
# Hero Settings
hero:
  title: Aaron's Blog
  description: Join me on my journey of exploration and learning.
  image: '/images/screen_diodes_glow_1176895_6000x4000.jpg'


#-------------------------------
# Contact Settings
contact:
  email: mpwazzav # Add your email for contact form
  description: If you have any questions, comments, or would like to discuss anything related to cybersecurity, reverse engineering, malware analysis, or CTF events, please feel free to reach out! I’m always excited to connect with fellow enthusiasts and professionals. You can contact me using the form below, and I will do my best to respond as soon as possible. Looking forward to hearing from you! # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/aaron-joiner"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/BinaryBobcat"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-ETVNKHPR0H # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join